apiVersion: integration/v1
kind: Step
name: cloud-run-deploy
version: 3
summary: Cloud run deploy

description: |
  Deploys a GCP cloud run service revision.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-cloud-run-deploy

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
  - summary: Deploy to Google Cloud Run
    content:
      apiVersion: v1
      kind: Step
      name: gcp-cloud-run-deploy
      image: relaysh/gcp-step-cloud-run-deploy
      spec:
        credentials:
          service-account.json: ${secrets.service-account-base64}
        project: ${parameters.gcpProject}
        service: ${parameters.serviceName}
        region: ${parameters.gcpRegion}
        image:
          repository: ${parameters.imageRepository}
          tag: ${parameters.imageTag}
