apiVersion: integration/v1
kind: Step
name: instance-reset
version: 3
summary: Reset instances

description: Resets a set of GCP compute instances.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-reset

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Reset a single compute instance in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: reset-instances
    image: relaysh/gcp-step-instance-reset
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
