apiVersion: integration/v1
kind: Step
name: disk-delete
version: 3
summary: Delete disk

description: Deletes a set of GCP disks.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-disk-delete

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Delete a single disk from a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: delete-disks
    image: relaysh/gcp-step-disk-delete
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      disks:
        - ${parameters.diskName}
