apiVersion: integration/v1
kind: Step
name: instance-start
version: 3
summary: Start instances

description: Starts a set of GCP compute instances.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-start

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Start a single compute instance in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: start-instances
    image: relaysh/gcp-step-instance-start
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
