apiVersion: integration/v1
kind: Step
name: instance-list
version: 3
summary: List instances

description: Lists the GCP compute instances under a project.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
- summary: List the compute instances in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: list-instances
    image: relaysh/gcp-step-instance-list
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
