apiVersion: integration/v1
kind: Step
name: instance-resume
version: 3
summary: Resume instances

description: Resumes a set of GCP compute instances using the beta API.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-resume

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Resume a single compute instance in a GCP account using the beta API
  content:
    apiVersion: v1
    kind: Step
    name: resume-instances
    image: relaysh/gcp-step-instance-resume
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
