apiVersion: integration/v1
kind: Step
name: instance-stop
version: 3
summary: Stop instances

description: Stops a set of GCP compute instances.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-stop

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Stop a single compute instance in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: stop-instances
    image: relaysh/gcp-step-instance-stop
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
