apiVersion: integration/v1
kind: Step
name: disk-list
version: 3
summary: List disks

description: Lists the GCP disks under a project.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-disk-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
- summary: List the disks in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: list-disks
    image: relaysh/gcp-step-disk-list
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
