apiVersion: integration/v1
kind: Step
name: instance-suspend
version: 1
summary: Suspend instances

description: Suspends a set of GCP compute instances using the Beta API

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-suspend

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Suspend a single compute instance in a GCP account using the Beta API
  content:
    apiVersion: v1
    kind: Step
    name: suspend-instances
    image: relaysh/gcp-step-instance-suspend
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
