apiVersion: integration/v1
kind: Step
name: instance-delete
version: 3
summary: Delete instances

description: Deletes a set of GCP compute instances.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/gcp-step-instance-delete

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Delete a single compute instance in a GCP account
  content:
    apiVersion: v1
    kind: Step
    name: delete-instances
    image: relaysh/gcp-step-instance-delete
    spec:
      google:
        service_account_info: ${connections.gcp.my-gcp-account}
        zone: ${parameters.gcpZone}
      instances:
        - ${parameters.instanceName}
